### ISSUE TITLE
Publicar a versão v1.0 do jogo para computador de mesa

### ISSUE THREAD

**Issue by ghost** [boidacarapreta/adcipt20221#41]
A versão `v1.0` do jogo deve ter:

- Hospedagem em GitHub Pages (#23) e Heroku (#32), conforme #25 - e iniciado em #31.
- Multijogador (#32).
- Suporte a salas de partida (#34 e #36).
- Áudio sobre WebRTC (#28).

**Comment by ghost** [comment]
Definida a _tag_ [`v1.0`](https://github.com/boidacarapreta/adcipt20221/releases/tag/v1.0).

**Comment by WBluan** [comment]
A versão do Jogo deve ter:

- Hospedagem em GitHub Pages e Heroku;
- Multijogador;
- Suporte a salas de partida;
- Áudio sobre WebRTC.

Commits com a versão 1.0 completa: 
<a href=411d74ebe93165c1bafa7b15993e89787e7a3ab0>WebRTC Funcionando</a>
<a href=9da8250d60b3829529604a3595c74f44bbf13cc7>Entrar na sala por botões</a>
